### ISSUE TITLE
Sign In Verification is not working for creating tasks

### ISSUE THREAD

**Issue by soobkwon** [breakbreakdown/webapp#20]
I've tried to use two of my gmail accounts and console says my sign in is still false with an error that has popped up. As someone has mentioned, the dialog box will not close, but I do get a verified message even though the gmail calendar has not added anything to both of my calendars.

<img width="1280" alt="screen shot 2018-06-04 at 3 09 45 pm" src="https://user-images.githubusercontent.com/24904480/40944539-0653702a-680a-11e8-87ad-453a1792768f.png">

**Comment by nogawb** [comment]
Was your popup blocker deactivated? When the event is created there should be a second popup which asks for your permission to add the event to your google calendar. If you already have given permission this popup will flash on the screen then automatically close. 

We tried replicating the problem and didnt encounter the same error, however it may be because all of our user accounts have already given permission to google. 

Thank you for your feedback!
